use_frameworks!

platform :ios, '8.0'

target 'XLBAlertView_Example' do
  pod 'XLBAlertView', :path => '../'

  target 'XLBAlertView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
